# Generated by Django 4.1 on 2022-08-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_folder_note_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
