# Generated by Django 4.1 on 2022-08-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_folder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(default='Unnamed Folder', max_length=100),
        ),
    ]
