# Generated by Django 4.1 on 2022-08-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_folder_description_alter_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.TextField(blank=True, default='unnamed note', null=True),
        ),
    ]
