# Generated by Django 4.1 on 2022-08-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_folder_description_alter_note_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
